# Multi-language support for Railway Emergency System

LANGUAGES = {
    'en': {
        'name': 'English',
        'code': 'en',
        'flag': '🇬🇧'
    },
    'hi': {
        'name': 'हिंदी',
        'code': 'hi',
        'flag': '🇮🇳'
    },
    'te': {
        'name': 'తెలుగు',
        'code': 'te',
        'flag': '🇮🇳'
    },
    'ta': {
        'name': 'தமிழ்',
        'code': 'ta',
        'flag': '🇮🇳'
    },
    'bn': {
        'name': 'বাংলা',
        'code': 'bn',
        'flag': '🇮🇳'
    },
    'ml': {
        'name': 'മലയാളം',
        'code': 'ml',
        'flag': '🇮🇳'
    }
}

TRANSLATIONS = {
    'en': {
        # Navigation
        'home': 'Home',
        'emergency': 'Emergency',
        'login': 'Login',
        'signup': 'Sign Up',
        'dashboard': 'Dashboard',
        'logout': 'Logout',
        'track_train': 'Track Train',
        
        # Emergency Form
        'report_emergency': 'Report Emergency',
        'passenger_name': 'Passenger Name',
        'phone_number': 'Phone Number',
        'train_number': 'Train Number',
        'coach_number': 'Coach Number',
        'seat_number': 'Seat Number',
        'emergency_type': 'Emergency Type',
        'description': 'Description',
        'submit_report': 'Submit Report',
        'get_location': 'Get My Location',
        
        # Emergency Types
        'heart_attack': 'Heart Attack',
        'breathing_difficulty': 'Breathing Difficulty',
        'severe_pain': 'Severe Pain',
        'unconscious': 'Unconscious',
        'injury_accident': 'Injury/Accident',
        'high_fever': 'High Fever',
        'sos': 'SOS - Critical Emergency',
        'other': 'Other',
        
        # Dashboard
        'emergency_reports': 'Emergency Reports',
        'total_reports': 'Total Reports',
        'sos_alerts': 'SOS Alerts',
        'pending': 'Pending',
        'resolved': 'Resolved',
        'system_status': 'System Status',
        'emergency_system': 'Emergency System',
        'train_tracking': 'Train Tracking',
        'station_network': 'Station Network',
        'operational': 'OPERATIONAL',
        'active': 'ACTIVE',
        'connected': 'CONNECTED',
        
        # Train Info
        'train_name': 'Train Name',
        'source_station': 'Source Station',
        'destination_station': 'Destination Station',
        'current_location': 'Current Location',
        'speed': 'Speed',
        'last_station': 'Last Station',
        'next_station': 'Next Station',
        'search_trains': 'Search Trains',
        'popular_trains': 'Popular Trains',
        
        # Medical Response
        'medical_response': 'Medical Response',
        'nearest_hospital': 'Nearest Hospital',
        'distance': 'Distance',
        'contact': 'Contact',
        'specialties': 'Specialties',
        'ambulance_available': 'Ambulance Available',
        'emergency_available': 'Emergency Available',
        
        # Status
        'in_progress': 'In Progress',
        'mark_resolved': 'Mark Resolved',
        'alert_manager': 'Alert Manager',
        'live_tracking': 'Live Tracking',
        
        # Messages
        'emergency_submitted': 'Emergency report submitted successfully!',
        'help_dispatched': 'Medical help has been dispatched to the nearest station.',
        'login_required': 'Please login to report emergency',
        'invalid_credentials': 'Invalid username or password',
        'account_created': 'Account created successfully',
        'username_exists': 'Username or email already exists',
        
        # Page Content
        'page_title': 'Emergency Medical Assistance for Railway Passengers',
        'page_subtitle': 'Quick access to medical help during train journey - Connecting passengers with railway authorities for immediate assistance',
        'for_passengers': 'For Passengers',
        'for_passengers_subtitle': 'यात्रियों के लिए',
        'passenger_services': 'Passenger Services',
        'passenger_desc': 'Login required to report emergencies, access SOS alerts, track your train',
        'login_to_access': 'Login to Access Portal',
        'for_authorities': 'For Railway Authorities',
        'for_authorities_subtitle': 'रेलवे अधिकारियों के लिए',
        'authority_dashboard': 'Authority Dashboard',
        'authority_desc': 'Monitor emergencies, coordinate medical response, track train locations',
        'access_authority': 'Access Authority Portal',
        
        # Dashboard Content
        'nearest_station': 'Nearest Station',
        'distance': 'Distance',
        'contact': 'Contact',
        'recommended_action': 'Recommended Action',
        'dispatch_medical_team': 'Dispatch medical team to',
        'calculating': 'Calculating...',
        'timeline': 'Timeline',
        'reported': 'Reported',
        'status': 'Status',
        'eta_to_station': 'ETA to Station',
        'minutes': 'minutes',
        'live_tracking': 'Live Tracking',
        'medical_response': 'Medical Response',
        'alert_manager': 'Alert Manager',
        'no_station_found': 'No Station Found',
        'mark_in_progress': 'Mark In Progress',
        'mark_resolved': 'Mark Resolved',
        'no_active_reports': 'No Active Emergency Reports',
        'all_systems_operational': 'All systems operational. No medical emergencies reported.',
        'last_updated': 'Last updated',
        'system_status': 'System Status',
        'emergency_system': 'Emergency System',
        'operational': 'OPERATIONAL',
        'active': 'ACTIVE',
        'station_network': 'Station Network',
        'connected': 'CONNECTED',
        'auto_refresh': 'Auto-Refresh',
        'seconds': 'SECONDS',
        
        # Additional Form Fields
        'emergency_details': 'Emergency Details',
        'location': 'Location (Optional)',
        'username': 'Username',
        
        # Station Master
        'for_station_masters': 'For Station Masters',
        'station_master_login': 'Station Master Login',
        'station_master_signin': 'Station Master Sign-in',
        'station_master_desc': 'Access your station\'s emergency reports and coordinate medical response',
        'station_code': 'Station Code',
        'password': 'Password',
        'sign_in': 'Sign In',
        'return_to_home': 'Return to home',
        'station_master_portal': 'Station Master Portal',
        'authorized_personnel': 'Authorized Personnel Only',
        'railway_emergency_system': 'Railway Emergency System',
        'station_master_console': 'Station Master Console',
        'station_emergency_management': 'Station emergency management & coordination',
        'passenger_site': 'Passenger Site',
        'emergency_reports_for_station': 'Emergency Reports for Station',
        'monitor_station_emergencies': 'Monitor emergencies approaching or at your station',
        'system_online': 'System: ONLINE',
        'station_information': 'Station Information',
        'station_name': 'Station Name',
        'contact_number': 'Contact Number',
        'medical_facility': 'Medical Facility',
        'station_overview': 'Station Overview',
        'approaching_trains': 'Approaching Trains',
        'pending_emergencies': 'Pending',
        'report_id': 'Report',
        'passenger': 'Passenger',
        'train': 'Train',
        'emergency': 'Emergency',
        'eta': 'ETA',
        'actions': 'Actions',
        'prepare_medical_team': 'Prepare Medical Team',
        'nearby_hospitals': 'Nearby Hospitals',
        'station_master_footer': 'Station Master Console',
        'no_emergency_reports': 'No emergency reports for your station',
        'station_master_dashboard': 'Station Master Dashboard',
        
        # Header & Footer
        'ministry_of_railways': 'Ministry of Railways',
        'emergency_support_system': 'Emergency Support System',
        'railway_medical_emergency_response': 'Railway Medical Emergency Response',
        'copyright': '© 2024 Railway Medical Emergency Response System. Ministry of Railways.',
        
        # Emergency Banner
        'medical_emergency_question': 'Medical Emergency?',
        'need_immediate_assistance': 'Need immediate medical assistance on train?',
        'report_emergency_immediately': 'Report your emergency immediately. Railway authorities will coordinate medical assistance at the nearest station.',
        'report_medical_emergency_btn': '🚨 Report Medical Emergency',
        'emergency_helpline': 'Emergency Helpline',
        'call': 'Call',
        'railway': 'Railway',
        'national_emergency': 'National Emergency',
        
        # Info Section
        'dedicated_system_desc': 'A dedicated system for reporting medical emergencies during train journeys. Station managers and railway officials can coordinate immediate medical assistance.',
        'passenger_login': 'Passenger Login',
        'admin_login': 'Admin Login',
        'station_managers_access': 'Station managers and authorized personnel can access the dashboard to:',
        'view_all_reports': 'View all emergency reports',
        'track_train_locations': 'Track train locations',
        'coordinate_response': 'Coordinate medical response',
        'monitor_emergencies': 'Station masters can monitor emergencies approaching their station:',
        'view_station_reports': 'View station-specific reports',
        'prepare_medical_teams': 'Prepare medical teams',
        'coordinate_local_response': 'Coordinate local response',
        
        # Quick Links
        'quick_links': 'Quick Links',
        'crowd_monitor': 'Crowd Monitor',
        'medical_bot': '🤖 Medical Bot',
        'all_services': 'All Services',
        'emergency_contacts': 'Emergency Contacts',
        'ambulance': 'Ambulance',
        
        # Important Info
        'important_information': 'Important Information',
        'life_threatening_warning': 'For Life-Threatening Emergencies',
        'call_helpline_immediately': 'Call emergency helpline 112 or railway helpline 139 immediately. Do not rely solely on this system for critical emergencies.',
        'system_limitations': 'This system assists in coordinating medical assistance but does not replace emergency medical services. Always call emergency services for immediate life-threatening situations.',
        
        # Authority Dashboard & Operations
        'operations_console': 'Operations Console',
        'monitor_reports_desc': 'Monitor incoming passenger reports, review train context, and update response status.',
        'system': 'System',
        'online': 'ONLINE',
        'offline': 'OFFLINE',
        'operational_overview': 'Operational Overview',
        'reports_queue': 'Reports Queue',
        'all': 'All',
        'not_available': 'Not available',
        'resolve': 'Resolve',
        'no_reports': 'No emergency reports found.',
        'system_notes': 'Notes: This dashboard uses the current database and simulated train context fallback when real APIs are unavailable.',
        
        # Station Master & Alerts
        'prepare_medical_confirm': 'Prepare medical team for Train',
        'medical_team_notified': 'Medical team has been notified and is preparing for arrival.',
        'emergency_reports_for': 'Emergency Reports for'
    },
    
    'hi': {
        # Navigation
        'home': 'होम',
        'emergency': 'आपातकाल',
        'login': 'लॉगिन',
        'signup': 'साइन अप',
        'dashboard': 'डैशबोर्ड',
        'logout': 'लॉगआउट',
        'track_train': 'ट्रेन ट्रैक करें',
        
        # Emergency Form
        'report_emergency': 'आपातकाल की रिपोर्ट करें',
        'passenger_name': 'यात्री का नाम',
        'phone_number': 'फोन नंबर',
        'train_number': 'ट्रेन नंबर',
        'coach_number': 'कोच नंबर',
        'seat_number': 'सीट नंबर',
        'emergency_type': 'आपातकाल का प्रकार',
        'description': 'विवरण',
        'submit_report': 'रिपोर्ट जमा करें',
        'get_location': 'मेरा स्थान प्राप्त करें',
        
        # Emergency Types
        'heart_attack': 'दिल का दौरा',
        'breathing_difficulty': 'सांस लेने में कठिनाई',
        'severe_pain': 'गंभीर दर्द',
        'unconscious': 'बेहोश',
        'injury_accident': 'चोट/दुर्घटना',
        'high_fever': 'तेज बुखार',
        'sos': 'SOS - गंभीर आपातकाल',
        'other': 'अन्य',
        
        # Dashboard
        'emergency_reports': 'आपातकालीन रिपोर्ट',
        'total_reports': 'कुल रिपोर्ट',
        'sos_alerts': 'SOS अलर्ट',
        'pending': 'लंबित',
        'resolved': 'हल हो गया',
        'system_status': 'सिस्टम स्थिति',
        'emergency_system': 'आपातकालीन सिस्टम',
        'train_tracking': 'ट्रेन ट्रैकिंग',
        'station_network': 'स्टेशन नेटवर्क',
        'operational': 'चालू',
        'active': 'सक्रिय',
        'connected': 'जुड़ा हुआ',
        
        # Train Info
        'train_name': 'ट्रेन का नाम',
        'source_station': 'प्रारंभिक स्टेशन',
        'destination_station': 'गंतव्य स्टेशन',
        'current_location': 'वर्तमान स्थान',
        'speed': 'गति',
        'last_station': 'पिछला स्टेशन',
        'next_station': 'अगला स्टेशन',
        'search_trains': 'ट्रेन खोजें',
        'popular_trains': 'लोकप्रिय ट्रेनें',
        
        # Medical Response
        'medical_response': 'चिकित्सा प्रतिक्रिया',
        'nearest_hospital': 'निकटतम अस्पताल',
        'distance': 'दूरी',
        'contact': 'संपर्क',
        'specialties': 'विशेषताएं',
        'ambulance_available': 'एम्बुलेंस उपलब्ध',
        'emergency_available': 'आपातकाल उपलब्ध',
        
        # Status
        'in_progress': 'प्रगति में',
        'mark_resolved': 'हल के रूप में चिह्नित करें',
        'alert_manager': 'मैनेजर को अलर्ट करें',
        'live_tracking': 'लाइव ट्रैकिंग',
        
        # Messages
        'emergency_submitted': 'आपातकालीन रिपोर्ट सफलतापूर्वक जमा की गई!',
        'help_dispatched': 'चिकित्सा सहायता निकटतम स्टेशन पर भेजी गई है।',
        'login_required': 'आपातकाल की रिपोर्ट करने के लिए कृपया लॉगिन करें',
        'invalid_credentials': 'गलत उपयोगकर्ता नाम या पासवर्ड',
        'account_created': 'खाता सफलतापूर्वक बनाया गया',
        'username_exists': 'उपयोगकर्ता नाम या ईमेल पहले से मौजूद है',
        
        # Page Content
        'page_title': 'रेलवे यात्रियों के लिए आपातकालीन चिकित्सा सहायता',
        'page_subtitle': 'ट्रेन यात्रा के दौरान चिकित्सा सहायता तक त्वरित पहुंच - तत्काल सहायता के लिए यात्रियों को रेलवे अधिकारियों से जोड़ना',
        'for_passengers': 'यात्रियों के लिए',
        'for_passengers_subtitle': 'यात्रियों के लिए',
        'passenger_services': 'यात्री सेवाएं',
        'passenger_desc': 'आपातकाल की रिपोर्ट करने, SOS अलर्ट एक्सेस करने, अपनी ट्रेन ट्रैक करने के लिए लॉगिन आवश्यक',
        'login_to_access': 'पोर्टल एक्सेस करने के लिए लॉगिन करें',
        'for_authorities': 'रेलवे अधिकारियों के लिए',
        'for_authorities_subtitle': 'रेलवे अधिकारियों के लिए',
        'authority_dashboard': 'प्राधिकरण डैशबोर्ड',
        'authority_desc': 'आपातकाल की निगरानी करें, चिकित्सा प्रतिक्रिया का समन्वय करें, ट्रेन स्थानों को ट्रैक करें',
        'access_authority': 'प्राधिकरण पोर्टल एक्सेस करें',
        
        # Dashboard Content
        'nearest_station': 'निकटतम स्टेशन',
        'distance': 'दूरी',
        'contact': 'संपर्क',
        'recommended_action': 'सुझाई गई कार्रवाई',
        'dispatch_medical_team': 'चिकित्सा टीम भेजें',
        'calculating': 'गणना की जा रही है...',
        'timeline': 'समयसीमा',
        'reported': 'रिपोर्ट किया गया',
        'status': 'स्थिति',
        'eta_to_station': 'स्टेशन पहुंचने का समय',
        'minutes': 'मिनट',
        'live_tracking': 'लाइव ट्रैकिंग',
        'medical_response': 'चिकित्सा प्रतिक्रिया',
        'alert_manager': 'मैनेजर को अलर्ट करें',
        'no_station_found': 'कोई स्टेशन नहीं मिला',
        'mark_in_progress': 'प्रगति में चिह्नित करें',
        'mark_resolved': 'हल के रूप में चिह्नित करें',
        'no_active_reports': 'कोई सक्रिय आपातकालीन रिपोर्ट नहीं',
        'all_systems_operational': 'सभी सिस्टम परिचालनीय। कोई चिकित्सा आपातकाल रिपोर्ट नहीं।',
        'last_updated': 'अंतिम अपडेट',
        'system_status': 'सिस्टम स्थिति',
        'emergency_system': 'आपातकालीन सिस्टम',
        'operational': 'परिचालनीय',
        'active': 'सक्रिय',
        'station_network': 'स्टेशन नेटवर्क',
        'connected': 'जुड़ा हुआ',
        'auto_refresh': 'ऑटो-रिफ्रेश',
        'seconds': 'सेकंड',
        
        # Additional Form Fields
        'emergency_details': 'आपातकालीन विवरण',
        'location': 'स्थान (वैकल्पिक)',
        'username': 'उपयोगकर्ता नाम',
        
        # Station Master
        'for_station_masters': 'स्टेशन मास्टर के लिए',
        'station_master_login': 'स्टेशन मास्टर लॉगिन',
        'station_master_signin': 'स्टेशन मास्टर साइन-इन',
        'station_master_desc': 'अपने स्टेशन की आपातकालीन रिपोर्ट एक्सेस करें और चिकित्सा प्रतिक्रिया का समन्वय करें',
        'station_code': 'स्टेशन कोड',
        'password': 'पासवर्ड',
        'sign_in': 'साइन इन',
        'return_to_home': 'होम पर वापस जाएं',
        'station_master_portal': 'स्टेशन मास्टर पोर्टल',
        'authorized_personnel': 'केवल अधिकृत कर्मचारी',
        'railway_emergency_system': 'रेलवे आपातकालीन प्रणाली',
        'station_master_console': 'स्टेशन मास्टर कंसोल',
        'station_emergency_management': 'स्टेशन आपातकालीन प्रबंधन और समन्वय',
        'passenger_site': 'यात्री साइट',
        'emergency_reports_for_station': 'स्टेशन के लिए आपातकालीन रिपोर्ट',
        'monitor_station_emergencies': 'अपने स्टेशन पर आने वाली या मौजूद आपात स्थितियों की निगरानी करें',
        'system_online': 'सिस्टम: ऑनलाइन',
        'station_information': 'स्टेशन जानकारी',
        'station_name': 'स्टेशन का नाम',
        'contact_number': 'संपर्क नंबर',
        'medical_facility': 'चिकित्सा सुविधा',
        'station_overview': 'स्टेशन अवलोकन',
        'approaching_trains': 'आने वाली ट्रेनें',
        'pending_emergencies': 'लंबित',
        'report_id': 'रिपोर्ट',
        'passenger': 'यात्री',
        'train': 'ट्रेन',
        'emergency': 'आपातकाल',
        'eta': 'पहुंचने का समय',
        'actions': 'कार्रवाई',
        'prepare_medical_team': 'चिकित्सा टीम तैयार करें',
        'nearby_hospitals': 'निकटवर्ती अस्पताल',
        'station_master_footer': 'स्टेशन मास्टर कंसोल',
        'no_emergency_reports': 'आपके स्टेशन के लिए कोई आपातकालीन रिपोर्ट नहीं',
        'station_master_dashboard': 'स्टेशन मास्टर डैशबोर्ड',
        
        # Header & Footer
        'ministry_of_railways': 'रेल मंत्रालय',
        'emergency_support_system': 'आपातकालीन सहायता प्रणाली',
        'railway_medical_emergency_response': 'रेलवे चिकित्सा आपातकालीन प्रतिक्रिया',
        'copyright': '© 2024 रेलवे चिकित्सा आपातकालीन प्रतिक्रिया प्रणाली। रेल मंत्रालय।',
        
        # Emergency Banner
        'medical_emergency_question': 'चिकित्सा आपातकाल?',
        'need_immediate_assistance': 'ट्रेन में तत्काल चिकित्सा सहायता की आवश्यकता है?',
        'report_emergency_immediately': 'अपनी आपात स्थिति की तुरंत रिपोर्ट करें। रेलवे प्राधिकरण निकटतम स्टेशन पर चिकित्सा सहायता का समन्वय करेंगे।',
        'report_medical_emergency_btn': '🚨 चिकित्सा आपातकाल की रिपोर्ट करें',
        'emergency_helpline': 'आपातकालीन हेल्पलाइन',
        'call': 'कॉल',
        'railway': 'रेलवे',
        'national_emergency': 'राष्ट्रीय आपातकाल',
        
        # Info Section
        'dedicated_system_desc': 'ट्रेन यात्रा के दौरान चिकित्सा आपात स्थितियों की रिपोर्ट करने के लिए एक समर्पित प्रणाली। स्टेशन मैनेजर और रेलवे अधिकारी तत्काल चिकित्सा सहायता का समन्वय कर सकते हैं।',
        'passenger_login': 'यात्री लॉगिन',
        'admin_login': 'एडमिन लॉगिन',
        'station_managers_access': 'स्टेशन मैनेजर और अधिकृत कर्मचारी डैशबोर्ड का उपयोग कर सकते हैं:',
        'view_all_reports': 'सभी आपातकालीन रिपोर्ट देखें',
        'track_train_locations': 'ट्रेन स्थानों को ट्रैक करें',
        'coordinate_response': 'चिकित्सा प्रतिक्रिया का समन्वय करें',
        'monitor_emergencies': 'स्टेशन मास्टर उनके स्टेशन की ओर आने वाली आपात स्थितियों की निगरानी कर सकते हैं:',
        'view_station_reports': 'स्टेशन-विशिष्ट रिपोर्ट देखें',
        'prepare_medical_teams': 'चिकित्सा टीमों को तैयार करें',
        'coordinate_local_response': 'स्थानीय प्रतिक्रिया का समन्वय करें',
        
        # Quick Links
        'quick_links': 'त्वरित लिंक',
        'crowd_monitor': 'भीड़ निगरानी',
        'medical_bot': '🤖 मेडिकल बॉट',
        'all_services': 'सभी सेवाएं',
        'emergency_contacts': 'आपातकालीन संपर्क',
        'ambulance': 'एम्बुलेंस',
        
        # Important Info
        'important_information': 'महत्वपूर्ण जानकारी',
        'life_threatening_warning': 'जीवन-धमकाने वाली आपात स्थितियों के लिए',
        'call_helpline_immediately': 'तुरंत आपातकालीन हेल्पलाइन 112 या रेलवे हेल्पलाइन 139 पर कॉल करें। गंभीर आपात स्थितियों के लिए केवल इस प्रणाली पर निर्भर न रहें।',
        'system_limitations': 'यह प्रणाली चिकित्सा सहायता के समन्वय में सहायता करती है लेकिन आपातकालीन चिकित्सा सेवाओं की जगह नहीं लेती है। तत्काल जीवन-धमकाने वाली स्थितियों के लिए हमेशा आपातकालीन सेवाओं को कॉल करें।',

        # Authority Dashboard & Operations
        'operations_console': 'ऑपरेशन्स कंसोल',
        'monitor_reports_desc': 'आने वाली यात्री रिपोर्टों की निगरानी करें, ट्रेन संदर्भ की समीक्षा करें, और प्रतिक्रिया स्थिति अपडेट करें।',
        'system': 'सिस्टम',
        'online': 'ऑनलाइन',
        'offline': 'ऑफलाइन',
        'operational_overview': 'परिचालन अवलोकन',
        'reports_queue': 'रिपोर्ट कतार',
        'all': 'सभी',
        'not_available': 'उपलब्ध नहीं',
        'resolve': 'हल करें',
        'no_reports': 'कोई आपातकालीन रिपोर्ट नहीं मिली।',
        'system_notes': 'नोट्स: यह डैशबोर्ड वास्तविक एपीआई अनुपलब्ध होने पर वर्तमान डेटाबेस और सिमुलेटेड ट्रेन संदर्भ का उपयोग करता है।',
        
        # Station Master & Alerts
        'prepare_medical_confirm': 'ट्रेन के लिए चिकित्सा टीम तैयार करें',
        'medical_team_notified': 'चिकित्सा टीम को सूचित कर दिया गया है और वे आगमन की तैयारी कर रहे हैं।',
        'emergency_reports_for': 'के लिए आपातकालीन रिपोर्ट'
    },
    
    'te': {
        # Navigation
        'home': 'హోమ్',
        'emergency': 'అత్యవసరం',
        'login': 'లాగిన్',
        'signup': 'సైన్ అప్',
        'dashboard': 'డాష్‌బోర్డ్',
        'logout': 'లాగ్అవుట్',
        'track_train': 'రైలు ట్రాక్ చేయండి',
        
        # Emergency Form
        'report_emergency': 'అత్యవసర పరిస్థితిని నివేదించండి',
        'passenger_name': 'ప్రయాణికుడి పేరు',
        'phone_number': 'ఫోన్ నంబర్',
        'train_number': 'రైలు నంబర్',
        'coach_number': 'కోచ్ నంబర్',
        'seat_number': 'సీటు నంబర్',
        'emergency_type': 'అత్యవసర రకం',
        'description': 'వివరణ',
        'submit_report': 'నివేదిక సమర్పించండి',
        'get_location': 'నా స్థానం పొందండి',
        
        # Emergency Types
        'heart_attack': 'గుండెపోటు',
        'breathing_difficulty': 'శ్వాస తీసుకోవడంలో ఇబ్బంది',
        'severe_pain': 'తీవ్రమైన నొప్పి',
        'unconscious': 'అపస్మారక స్థితి',
        'injury_accident': 'గాయం/ప్రమాదం',
        'high_fever': 'అధిక జ్వరం',
        'sos': 'SOS - క్రిటికల్ అత్యవసరం',
        'other': 'ఇతర',
        
        # Dashboard
        'emergency_reports': 'అత్యవసర నివేదికలు',
        'total_reports': 'మొత్తం నివేదికలు',
        'sos_alerts': 'SOS అలర్ట్‌లు',
        'pending': 'పెండింగ్',
        'resolved': 'పరిష్కరించబడింది',
        'system_status': 'సిస్టమ్ స్థితి',
        'emergency_system': 'అత్యవసర వ్యవస్థ',
        'train_tracking': 'రైలు ట్రాకింగ్',
        'station_network': 'స్టేషన్ నెట్‌వర్క్',
        'operational': 'పనిచేస్తోంది',
        'active': 'క్రియాశీలం',
        'connected': 'కనెక్ట్ చేయబడింది',
        
        # Train Info
        'train_name': 'రైలు పేరు',
        'source_station': 'మూల స్టేషన్',
        'destination_station': 'గమ్యస్థాన స్టేషన్',
        'current_location': 'ప్రస్తుత స్థానం',
        'speed': 'వేగం',
        'last_station': 'చివరి స్టేషన్',
        'next_station': 'తదుపరి స్టేషన్',
        'search_trains': 'రైళ్లను వెతకండి',
        'popular_trains': 'ప్రసిద్ధ రైళ్లు',
        
        # Medical Response
        'medical_response': 'వైద్య ప్రతిస్పందన',
        'nearest_hospital': 'సమీప ఆసుపత్రి',
        'distance': 'దూరం',
        'contact': 'సంప్రదింపు',
        'specialties': 'ప్రత్యేకతలు',
        'ambulance_available': 'అంబులెన్స్ అందుబాటులో ఉంది',
        'emergency_available': 'అత్యవసరం అందుబాటులో ఉంది',
        
        # Status
        'in_progress': 'పురోగతిలో ఉంది',
        'mark_resolved': 'పరిష్కరించబడినట్లు గుర్తించండి',
        'alert_manager': 'మేనేజర్‌ను అలర్ట్ చేయండి',
        'live_tracking': 'లైవ్ ట్రాకింగ్',
        
        # Messages
        'emergency_submitted': 'అత్యవసర నివేదిక విజయవంతంగా సమర్పించబడింది!',
        'help_dispatched': 'వైద్య సహాయం సమీప స్టేషన్‌కు పంపబడింది.',
        'login_required': 'అత్యవసరం నివేదించడానికి దయచేసి లాగిన్ చేయండి',
        'invalid_credentials': 'తప్పుడు వినియోగదారు పేరు లేదా పాస్‌వర్డ్',
        'account_created': 'ఖాతా విజయవంతంగా సృష్టించబడింది',
        'username_exists': 'వినియోగదారు పేరు లేదా ఇమెయిల్ ఇప్పటికే ఉంది',
        
        # Page Content
        'page_title': 'రైలు ప్రయాణికుల కోసం అత్యవసర వైద్య సహాయం',
        'page_subtitle': 'రైలు ప్రయాణంలో వైద్య సహాయానికి త్వరిత ప్రవేశం - తక్షణ సహాయం కోసం ప్రయాణికులను రైల్వే అధికారులతో కనెక్ట్ చేయడం',
        'for_passengers': 'ప్రయాణికుల కోసం',
        'for_passengers_subtitle': 'ప్రయాణికుల కోసం',
        'passenger_services': 'ప్రయాణికుల సేవలు',
        'passenger_desc': 'అత్యవసర పరిస్థితులను నివేదించడానికి, SOS అలర్ట్లను యాక్సెస్ చేయడానికి, మీ రైలును ట్రాక్ చేయడానికి లాగిన్ అవసరం',
        'login_to_access': 'పోర్టల్ యాక్సెస్ చేయడానికి లాగిన్ చేయండి',
        'for_authorities': 'రైల్వే అధికారుల కోసం',
        'for_authorities_subtitle': 'రైల్వే అధికారుల కోసం',
        'authority_dashboard': 'అధికార డాష్బోర్డ్',
        'authority_desc': 'అత్యవసర పరిస్థితులను పర్యవేక్షించండి, వైద్య ప్రతిస్పందనను సమన్వయం చేయండి, రైలు స్థానాలను ట్రాక్ చేయండి',
        'access_authority': 'అధికార పోర్టల్ యాక్సెస్ చేయండి',
        
        # Dashboard Content
        'nearest_station': 'సమీప స్టేషన్',
        'distance': 'దూరం',
        'contact': 'సంప్రదింపు',
        'recommended_action': 'సూచించబడిన క్రమం',
        'dispatch_medical_team': 'వైద్య టీమ్ పంపండి',
        'calculating': 'లెక్కించుతున్నాము...',
        'timeline': 'సమయ రేఖ',
        'reported': 'నివేదించబడింది',
        'status': 'స్థితి',
        'eta_to_station': 'స్టేషన్ కు సమయం',
        'minutes': 'నిమిషాలు',
        'live_tracking': 'లైవ్ ట్రాకింగ్',
        'medical_response': 'వైద్య ప్రతిస్పందన',
        'alert_manager': 'మానేజర్ను అలర్ట్ చేయండి',
        'no_station_found': 'స్టేషన్ కనుగొనబడలేదు',
        'mark_in_progress': 'పురోగతిలో గుర్తించండి',
        'mark_resolved': 'పరిష్కరించబడినదిగా గుర్తించండి',
        'no_active_reports': 'సక్రియ అత్యవసర నివేదికలు లేవు',
        'all_systems_operational': 'అన్ని సిస్టమ్లు పరిచాలనలో ఉన్నాయి. వైద్య అత్యవసరాలు నివేదించబడలేదు.',
        'last_updated': 'కొత్తగా అప్డేట్',
        'system_status': 'సిస్టమ్ స్థితి',
        'emergency_system': 'అత్యవసర వ్యవస్థ',
        'operational': 'పరిచాలనలో',
        'active': 'సక్రియం',
        'station_network': 'స్టేషన్ నెట్వర్క్',
        'connected': 'కనెక్ట్ అయ్యింది',
        'auto_refresh': 'ఆటో-రిఫ్రెష్',
        'seconds': 'సెకన్లు',
        
        # Additional Form Fields
        'emergency_details': 'అత్యవసర వివరాలు',
        'location': 'స్థానం (ఐచ్ఛికం)',
        'username': 'వినియోగదారు పేరు',
        
        # Station Master
        'for_station_masters': 'స్టేషన్ మాస్టర్ల కోసం',
        'station_master_login': 'స్టేషన్ మాస్టర్ లాగిన్',
        'station_master_signin': 'స్టేషన్ మాస్టర్ సైన్-ఇన్',
        'station_master_desc': 'మీ స్టేషన్ అత్యవసర నివేదికలను యాక్సెస్ చేయండి మరియు వైద్య ప్రతిస్పందనను సమన్వయం చేయండి',
        'station_code': 'స్టేషన్ కోడ్',
        'password': 'పాస్‌వర్డ్',
        'sign_in': 'సైన్ ఇన్',
        'return_to_home': 'హోమ్‌కు తిరిగి వెళ్ళండి',
        'station_master_portal': 'స్టేషన్ మాస్టర్ పోర్టల్',
        'authorized_personnel': 'అధికార కర్మచారులు మాత్రమే',
        'railway_emergency_system': 'రైల్వే అత్యవసర వ్యవస్థ',
        'station_master_console': 'స్టేషన్ మాస్టర్ కన్సోల్',
        'station_emergency_management': 'స్టేషన్ అత్యవసర నిర్వహణ & సమన్వయం',
        'passenger_site': 'ప్రయాణికుల సైట్',
        'emergency_reports_for_station': 'స్టేషన్ కోసం అత్యవసర నివేదికలు',
        'monitor_station_emergencies': 'మీ స్టేషన్‌కు చేరుకునే లేదా ఉన్న అత్యవసర పరిస్థితులను పర్యవేక్షించండి',
        'system_online': 'సిస్టమ్: ఆన్‌లైన్',
        'station_information': 'స్టేషన్ సమాచారం',
        'station_name': 'స్టేషన్ పేరు',
        'contact_number': 'సంప్రదింపు నంబర్',
        'medical_facility': 'వైద్య సౌకర్యం',
        'station_overview': 'స్టేషన్ అవలోకనం',
        'approaching_trains': 'చేరుకుంటున్న రైళ్లు',
        'pending_emergencies': 'పెండింగ్',
        'report_id': 'నివేదిక',
        'passenger': 'ప్రయాణికుడు',
        'train': 'రైలు',
        'emergency': 'అత్యవసరం',
        'eta': 'చేరుకునే సమయం',
        'actions': 'చర్యలు',
        'prepare_medical_team': 'వైద్య బృందాన్ని సిద్ధం చేయండి',
        'nearby_hospitals': 'సమీప ఆసుపత్రులు',
        'station_master_footer': 'స్టేషన్ మాస్టర్ కన్సోల్',
        'no_emergency_reports': 'మీ స్టేషన్ కోసం అత్యవసర నివేదికలు లేవు',
        'station_master_dashboard': 'స్టేషన్ మాస్టర్ డాష్‌బోర్డ్',
        
        # Header & Footer
        'ministry_of_railways': 'రైల్వే మంత్రిత్వ శాఖ',
        'emergency_support_system': 'అత్యవసర మద్దతు వ్యవస్థ',
        'railway_medical_emergency_response': 'రైల్వే వైద్య అత్యవసర ప్రతిస్పందన',
        'copyright': '© 2024 రైల్వే వైద్య అత్యవసర ప్రతిస్పందన వ్యవస్థ. రైల్వే మంత్రిత్వ శాఖ.',
        
        # Emergency Banner
        'medical_emergency_question': 'వైద్య అత్యవసర పరిస్థితి?',
        'need_immediate_assistance': 'రైలులో తక్షణ వైద్య సహాయం కావాలా?',
        'report_emergency_immediately': 'మీ అత్యవసర పరిస్థితిని వెంటనే నివేదించండి. రైల్వే అధికారులు సమీపంలోని స్టేషన్‌లో వైద్య సహాయాన్ని సమన్వయం చేస్తారు.',
        'report_medical_emergency_btn': '🚨 వైద్య అత్యవసర పరిస్థితిని నివేదించండి',
        'emergency_helpline': 'అత్యవసర హెల్ప్‌లైన్',
        'call': 'కాల్',
        'railway': 'రైల్వే',
        'national_emergency': 'జాతీయ అత్యవసరం',
        
        # Info Section
        'dedicated_system_desc': 'రైలు ప్రయాణాల్లో వైద్య అత్యవసర పరిస్థితులను నివేదించడానికి అంకితమైన వ్యవస్థ. స్టేషన్ మేనేజర్లు మరియు రైల్వే అధికారులు తక్షణ వైద్య సహాయాన్ని సమన్వయం చేయవచ్చు.',
        'passenger_login': 'ప్రయాణికుల లాగిన్',
        'admin_login': 'అడ్మిన్ లాగిన్',
        'station_managers_access': 'స్టేషన్ మేనేజర్లు మరియు అర్హత కలిగిన సిబ్బంది డాష్‌బోర్డ్‌ను యాక్సెస్ చేయవచ్చు:',
        'view_all_reports': 'అన్ని అత్యవసర నివేదికలను వీక్షించండి',
        'track_train_locations': 'రైలు స్థానాలను ట్రాక్ చేయండి',
        'coordinate_response': 'వైద్య ప్రతిస్పందనను సమన్వయం చేయండి',
        'monitor_emergencies': 'స్టేషన్ మాస్టర్లు తమ స్టేషన్‌కు వచ్చే అత్యవసర పరిస్థితులను పర్యవేక్షించవచ్చు:',
        'view_station_reports': 'స్టేషన్-వారీ నివేదికలను వీక్షించండి',
        'prepare_medical_teams': 'వైద్య బృందాలను సిద్ధం చేయండి',
        'coordinate_local_response': 'స్థానిక ప్రతిస్పందనను సమన్వయం చేయండి',
        
        # Quick Links
        'quick_links': 'త్వరిత లింకులు',
        'crowd_monitor': 'క్రౌడ్ మానిటర్',
        'medical_bot': '🤖 మెడికల్ బాట్',
        'all_services': 'అన్ని సేవలు',
        'emergency_contacts': 'అత్యవసర సంప్రదింపులు',
        'ambulance': 'అంబులెన్స్',
        
        # Important Info
        'important_information': 'ముఖ్యమైన సమాచారం',
        'life_threatening_warning': 'ప్రాణాంతక అత్యవసర పరిస్థితుల కోసం',
        'call_helpline_immediately': 'వెంటనే అత్యవసర హెల్ప్‌లైన్ 112 లేదా రైల్వే హెల్ప్‌లైన్ 139 కి కాల్ చేయండి. క్లిష్టమైన అత్యవసర పరిస్థితుల కోసం ఈ వ్యవస్థపై మాత్రమే ఆధారపడవద్దు.',
        'system_limitations': 'ఈ వ్యవస్థ వైద్య సహాయాన్ని సమన్వయం చేయడంలో సహాయపడుతుంది కానీ అత్యవసర వైద్య సేవలను భర్తీ చేయదు. తక్షణ ప్రాణాంతక పరిస్థితుల కోసం ఎల్లప్పుడూ అత్యవసర సేవలకు కాల్ చేయండి.'
    },
    
    'ta': {
        # Navigation
        'home': 'முகப்பு',
        'emergency': 'அவசரநிலை',
        'login': 'உள்நுழைவு',
        'signup': 'பதிவு செய்யவும்',
        'dashboard': 'டாஷ்போர்டு',
        'logout': 'வெளியேறு',
        'track_train': 'ரயிலைக் கண்காணிக்கவும்',
        
        # Emergency Form
        'report_emergency': 'அவசரநிலையைப் புகாரளிக்கவும்',
        'passenger_name': 'பயணியின் பெயர்',
        'phone_number': 'தொலைபேசி எண்',
        'train_number': 'ரயில் எண்',
        'coach_number': 'பெட்டி எண்',
        'seat_number': 'இருக்கை எண்',
        'emergency_type': 'அவசர வகை',
        'description': 'விளக்கம்',
        'submit_report': 'அறிக்கையை சமர்பிக்கவும்',
        'get_location': 'எனது இருப்பிடத்தைப் பெறவும்',
        
        # Emergency Types
        'heart_attack': 'மாரடைப்பு',
        'breathing_difficulty': 'சுவாசிப்பதில் சிரமம்',
        'severe_pain': 'கடுமையான வலி',
        'unconscious': 'மயக்கநிலை',
        'injury_accident': 'காயம்/விபத்து',
        'high_fever': 'அதிக காய்ச்சல்',
        'sos': 'SOS - முக்கியமான அவசரநிலை',
        'other': 'மற்றவை',
        
        # Dashboard
        'emergency_reports': 'அவசர அறிக்கைகள்',
        'total_reports': 'மொத்த அறிக்கைகள்',
        'sos_alerts': 'SOS எச்சரிக்கைகள்',
        'pending': 'நிலுவையில்',
        'resolved': 'தீர்க்கப்பட்டது',
        'system_status': 'கணினி நிலை',
        'emergency_system': 'அவசர அமைப்பு',
        'train_tracking': 'ரயில் கண்காணிப்பு',
        'station_network': 'நிலைய வலையமைப்பு',
        'operational': 'செயல்பாட்டில்',
        'active': 'செயலில்',
        'connected': 'இணைக்கப்பட்டது',
        
        # Train Info
        'train_name': 'ரயிலின் பெயர்',
        'source_station': 'தொடக்க நிலையம்',
        'destination_station': 'இலக்கு நிலையம்',
        'current_location': 'தற்போதைய இருப்பிடம்',
        'speed': 'வேகம்',
        'last_station': 'கடைசி நிலையம்',
        'next_station': 'அடுத்த நிலையம்',
        'search_trains': 'ரயில்களைத் தேடவும்',
        'popular_trains': 'பிரபலமான ரயில்கள்',
        
        # Medical Response
        'medical_response': 'மருத்துவ பதில்',
        'nearest_hospital': 'அருகிலுள்ள மருத்துவமனை',
        'distance': 'தூரம்',
        'contact': 'தொடர்பு',
        'specialties': 'சிறப்புகள்',
        'ambulance_available': 'ஆம்புலன்ஸ் கிடைக்கிறது',
        'emergency_available': 'அவசரநிலை கிடைக்கிறது',
        
        # Status
        'in_progress': 'முன்னேற்றத்தில்',
        'mark_resolved': 'தீர்க்கப்பட்டதாகக் குறிக்கவும்',
        'alert_manager': 'மேலாளரை எச்சரிக்கவும்',
        'live_tracking': 'நேரடி கண்காணிப்பு',
        
        # Messages
        'emergency_submitted': 'அவசர அறிக்கை வெற்றிகரமாக சமர்பிக்கப்பட்டது!',
        'help_dispatched': 'மருத்துவ உதவி அருகிலுள்ள நிலையத்திற்கு அனுப்பப்பட்டது.',
        'login_required': 'அவசரநிலையைப் புகாரளிக்க தயவுசெய்து உள்நுழையவும்',
        'invalid_credentials': 'தவறான பயனர்பெயர் அல்லது கடவுச்சொல்',
        'account_created': 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
        'username_exists': 'பயனர்பெயர் அல்லது மின்னஞ்சல் ஏற்கனவே உள்ளது',
        
        # Page Content
        'page_title': 'ரயில் பயணிகளுக்கான அவசர மருத்துவ உதவி',
        'page_subtitle': 'ரயில் பயணத்தின் போது மருத்துவ உதவிக்கான விரைவான அணுகல் - உடனடி உதவிக்காக பயணிகளை ரயில்வே அதிகாரிகளுடன் இணைத்தல்',
        'for_passengers': 'பயணிகளுக்கு',
        'for_passengers_subtitle': 'பயணிகளுக்கு',
        'passenger_services': 'பயணிகள் சேவைகள்',
        'passenger_desc': 'அவசரநிலைகளைப் புகாரளிக்க, SOS எச்சரிக்கைகளை அணுக, உங்கள் ரயிலைக் கண்காணிக்க உள்நுழைவு தேவை',
        'login_to_access': 'போர்ட்டலை அணுக உள்நுழையவும்',
        'for_authorities': 'ரயில்வே அதிகாரிகளுக்கு',
        'for_authorities_subtitle': 'ரயில்வே அதிகாரிகளுக்கு',
        'authority_dashboard': 'அதிகார டாஷ்போர்டு',
        'authority_desc': 'அவசரநிலைகளைக் கண்காணிக்கவும், மருத்துவ பதிலை ஒருங்கிணைக்கவும், ரயில் இருப்பிடங்களைக் கண்காணிக்கவும்',
        'access_authority': 'அதிகார போர்ட்டலை அணுகவும்',
        
        # Dashboard Content
        'nearest_station': 'அருகிலுள்ள நிலையம்',
        'distance': 'தூரம்',
        'contact': 'தொடர்பு',
        'recommended_action': 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
        'dispatch_medical_team': 'மருத்துவ குழுவை அனுப்பவும்',
        'calculating': 'கணக்கீடு செய்யப்படுகிறது...',
        'timeline': 'கால வரிசை',
        'reported': 'அறிவிக்கப்பட்டது',
        'status': 'நிலை',
        'eta_to_station': 'நிலையத்திற்கு எதிர்பார்க்கும் நேரம்',
        'minutes': 'நிமிடங்கள்',
        'live_tracking': 'நேரடி கண்காணிப்பு',
        'medical_response': 'மருத்துவ பதில்',
        'alert_manager': 'மேலாளரை எச்சரிக்கவும்',
        'no_station_found': 'நிலையம் கண்டுபிடிக்கவில்லை',
        'mark_in_progress': 'முன்னேற்றத்தில் குறிக்கவும்',
        'mark_resolved': 'தீர்க்கப்பட்டதாகக் குறிக்கவும்',
        'no_active_reports': 'செயல்பாட்டிலுள்ள அவசர அறிக்கைகள் இல்லை',
        'all_systems_operational': 'அனைத்து அமைப்புகளும் இயங்குகின்றன. மருத்துவ அவசரநிலைகள் அறிவிக்கப்படவில்லை.',
        'last_updated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
        'system_status': 'அமைப்பு நிலை',
        'emergency_system': 'அவசர அமைப்பு',
        'operational': 'இயங்குகிறது',
        'active': 'செயலில்',
        'station_network': 'நிலைய வலையமைப்பு',
        'connected': 'இணைக்கப்பட்டுள்ளது',
        'auto_refresh': 'தானியங்கி புதுப்பிப்பு',
        'seconds': 'விநாடிகள்',
        
        # Additional Form Fields
        'emergency_details': 'அவசர விவரங்கள்',
        'location': 'இருப்பிடம் (விருப்பமானது)',
        'username': 'பயனர்பெயர்',
        
        # Station Master
        'for_station_masters': 'நிலைய மாஸ்டர்களுக்கு',
        'station_master_login': 'நிலைய மாஸ்டர் உள்நுழைவு',
        'station_master_signin': 'நிலைய மாஸ்டர் உள்நுழைவு',
        'station_master_desc': 'உங்கள் நிலையத்தின் அவசர அறிக்கைகளை அணுகவும் மற்றும் மருத்துவ பதிலை ஒருங்கிணைக்கவும்',
        'station_code': 'நிலைய குறியீடு',
        'password': 'கடவுச்சொல்',
        'sign_in': 'உள்நுழைக',
        'return_to_home': 'முகப்புக்குத் திரும்பு',
        'station_master_portal': 'நிலைய மாஸ்டர் போர்ட்டல்',
        'authorized_personnel': 'அங்கீகரிக்கப்பட்ட பணியாளர்கள் மட்டும்',
        'railway_emergency_system': 'ரயில்வே அவசர அமைப்பு',
        'station_master_console': 'நிலைய மாஸ்டர் கன்சோல்',
        'station_emergency_management': 'நிலைய அவசர மேலாண்மை மற்றும் ஒருங்கிணைப்பு',
        'passenger_site': 'பயணிகள் தளம்',
        'emergency_reports_for_station': 'நிலையத்திற்கான அவசர அறிக்கைகள்',
        'monitor_station_emergencies': 'உங்கள் நிலையத்தை நெருங்கும் அல்லது உள்ள அவசரநிலைகளைக் கண்காணிக்கவும்',
        'system_online': 'அமைப்பு: ஆன்லைன்',
        'station_information': 'நிலைய தகவல்',
        'station_name': 'நிலையத்தின் பெயர்',
        'contact_number': 'தொடர்பு எண்',
        'medical_facility': 'மருத்துவ வசதி',
        'station_overview': 'நிலைய கண்ணோட்டம்',
        'approaching_trains': 'நெருங்கும் ரயில்கள்',
        'pending_emergencies': 'நிலுவையில்',
        'report_id': 'அறிக்கை',
        'passenger': 'பயணி',
        'train': 'ரயில்',
        'emergency': 'அவசரநிலை',
        'eta': 'எதிர்பார்க்கும் நேரம்',
        'actions': 'செயல்கள்',
        'prepare_medical_team': 'மருத்துவ குழுவை தயார் செய்யவும்',
        'nearby_hospitals': 'அருகிலுள்ள மருத்துவமனைகள்',
        'station_master_footer': 'நிலைய மாஸ்டர் கன்சோல்',
        'no_emergency_reports': 'உங்கள் நிலையத்திற்கு அவசர அறிக்கைகள் இல்லை',
        'station_master_dashboard': 'நிலைய மாஸ்டர் டாஷ்போர்டு',
        
        # Header & Footer
        'ministry_of_railways': 'ரயில்வே அமைச்சகம்',
        'emergency_support_system': 'அவசர ஆதரவு அமைப்பு',
        'railway_medical_emergency_response': 'ரயில்வே மருத்துவ அவசர பதில்',
        'copyright': '© 2024 ரயில்வே மருத்துவ அவசர பதில் அமைப்பு. ரயில்வே அமைச்சகம்.',
        
        # Emergency Banner
        'medical_emergency_question': 'மருத்துவ அவசரநிலை?',
        'need_immediate_assistance': 'ரயிலில் உடனடி மருத்துவ உதவி தேவையா?',
        'report_emergency_immediately': 'உங்கள் அவசரநிலையை உடனடியாகப் புகாரளிக்கவும். ரயில்வே அதிகாரிகள் அருகிலுள்ள நிலையத்தில் மருத்துவ உதவியை ஒருங்கிணைப்பார்கள்.',
        'report_medical_emergency_btn': '🚨 மருத்துவ அவசரநிலையைப் புகாரளிக்கவும்',
        'emergency_helpline': 'அவசர உதவி எண்',
        'call': 'அழைப்பு',
        'railway': 'ரயில்வே',
        'national_emergency': 'தேசிய அவசரநிலை',
        
        # Info Section
        'dedicated_system_desc': 'ரயில் பயணங்களின் போது மருத்துவ அவசரநிலைகளைப் புகாரளிக்க அர்ப்பணிக்கப்பட்ட அமைப்பு. நிலைய மேலாளர்கள் மற்றும் ரயில்வே அதிகாரிகள் உடனடி மருத்துவ உதவியை ஒருங்கிணைக்க முடியும்.',
        'passenger_login': 'பயணி உள்நுழைவு',
        'admin_login': 'நிர்வாகி உள்நுழைவு',
        'station_managers_access': 'நிலைய மேலாளர்கள் மற்றும் அங்கீகரிக்கப்பட்ட பணியாளர்கள் டாஷ்போர்டை அணுகலாம்:',
        'view_all_reports': 'அனைத்து அவசர அறிக்கைகளையும் காண்க',
        'track_train_locations': 'ரயில் இருப்பிடங்களைக் கண்காணிக்கவும்',
        'coordinate_response': 'மருத்துவ பதிலை ஒருங்கிணைக்கவும்',
        'monitor_emergencies': 'நிலைய மாஸ்டர்கள் தங்கள் நிலையத்தை நெருங்கும் அவசரநிலைகளைக் கண்காணிக்கலாம்:',
        'view_station_reports': 'நிலையம் சார்ந்த அறிக்கைகளைக் காண்க',
        'prepare_medical_teams': 'மருத்துவ குழுக்களை தயார் செய்யவும்',
        'coordinate_local_response': 'உள்ளூர் பதிலை ஒருங்கிணைக்கவும்',
        
        # Quick Links
        'quick_links': 'விரைவு இணைப்புகள்',
        'crowd_monitor': 'கூட்ட கண்காணிப்பு',
        'medical_bot': '🤖 மருத்துவ பாட்',
        'all_services': 'அனைத்து சேவைகள்',
        'emergency_contacts': 'அவசரத் தொடர்புகள்',
        'ambulance': 'ஆம்புலன்ஸ்',
        
        # Important Info
        'important_information': 'முக்கியமான தகவல்',
        'life_threatening_warning': 'உயிருக்கு ஆபத்தான அவசரநிலைகளுக்கு',
        'call_helpline_immediately': 'உடனடியாக அவசர உதவி எண் 112 அல்லது ரயில்வே உதவி எண் 139 ஐ அழைக்கவும். முக்கியமான அவசரநிலைகளுக்கு இந்த அமைப்பை மட்டும் நம்ப வேண்டாம்.',
        'system_limitations': 'இந்த அமைப்பு மருத்துவ உதவியை ஒருங்கிணைக்க உதவுகிறது ஆனால் அவசர மருத்துவ சேவைகளை மாற்றாது. உடனடி உயிருக்கு ஆபத்தான சூழ்நிலைகளுக்கு எப்போதும் அவசர சேவைகளை அழைக்கவும்.'
    },
    
    'bn': {
        # Navigation
        'home': 'হোম',
        'emergency': 'জরুরি অবস্থা',
        'login': 'লগইন',
        'signup': 'সাইন আপ',
        'dashboard': 'ড্যাশবোর্ড',
        'logout': 'লগআউট',
        'track_train': 'ট্রেন ট্র্যাক করুন',
        
        # Emergency Form
        'report_emergency': 'জরুরি অবস্থার রিপোর্ট করুন',
        'passenger_name': 'যাত্রীর নাম',
        'phone_number': 'ফোন নম্বর',
        'train_number': 'ট্রেন নম্বর',
        'coach_number': 'কোচ নম্বর',
        'seat_number': 'সিট নম্বর',
        'emergency_type': 'জরুরি অবস্থার ধরন',
        'description': 'বিবরণ',
        'submit_report': 'রিপোর্ট জমা দিন',
        'get_location': 'আমার অবস্থান পান',
        
        # Emergency Types
        'heart_attack': 'হার্ট অ্যাটাক',
        'breathing_difficulty': 'শ্বাসকষ্ট',
        'severe_pain': 'তীব্র ব্যথা',
        'unconscious': 'অজ্ঞান',
        'injury_accident': 'আঘাত/দুর্ঘটনা',
        'high_fever': 'উচ্চ জ্বর',
        'sos': 'SOS - গুরুতর জরুরি অবস্থা',
        'other': 'অন্যান্য',
        
        # Dashboard
        'emergency_reports': 'জরুরি রিপোর্ট',
        'total_reports': 'মোট রিপোর্ট',
        'sos_alerts': 'SOS সতর্কতা',
        'pending': 'অপেক্ষমান',
        'resolved': 'সমাধান হয়েছে',
        'system_status': 'সিস্টেমের অবস্থা',
        'emergency_system': 'জরুরি সিস্টেম',
        'train_tracking': 'ট্রেন ট্র্যাকিং',
        'station_network': 'স্টেশন নেটওয়ার্ক',
        'operational': 'চালু',
        'active': 'সক্রিয়',
        'connected': 'সংযুক্ত',
        
        # Train Info
        'train_name': 'ট্রেনের নাম',
        'source_station': 'উৎস স্টেশন',
        'destination_station': 'গন্তব্য স্টেশন',
        'current_location': 'বর্তমান অবস্থান',
        'speed': 'গতি',
        'last_station': 'শেষ স্টেশন',
        'next_station': 'পরবর্তী স্টেশন',
        'search_trains': 'ট্রেন খুঁজুন',
        'popular_trains': 'জনপ্রিয় ট্রেন',
        
        # Medical Response
        'medical_response': 'চিকিৎসা প্রতিক্রিয়া',
        'nearest_hospital': 'নিকটতম হাসপাতাল',
        'distance': 'দূরত্ব',
        'contact': 'যোগাযোগ',
        'specialties': 'বিশেষত্ব',
        'ambulance_available': 'অ্যাম্বুলেন্স উপলব্ধ',
        'emergency_available': 'জরুরি অবস্থা উপলব্ধ',
        
        # Status
        'in_progress': 'চলমান',
        'mark_resolved': 'সমাধান হিসেবে চিহ্নিত করুন',
        'alert_manager': 'ম্যানেজারকে সতর্ক করুন',
        'live_tracking': 'লাইভ ট্র্যাকিং',
        
        # Messages
        'emergency_submitted': 'জরুরি রিপোর্ট সফলভাবে জমা দেওয়া হয়েছে!',
        'help_dispatched': 'চিকিৎসা সহায়তা নিকটতম স্টেশনে পাঠানো হয়েছে।',
        'login_required': 'জরুরি অবস্থার রিপোর্ট করতে দয়া করে লগইন করুন',
        'invalid_credentials': 'ভুল ব্যবহারকারীর নাম বা পাসওয়ার্ড',
        'account_created': 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
        'username_exists': 'ব্যবহারকারীর নাম বা ইমেইল ইতিমধ্যে বিদ্যমান',
        
        # Page Content
        'page_title': 'রেল যাত্রীদের জন্য জরুরি চিকিৎসা সহায়তা',
        'page_subtitle': 'ট্রেন যাত্রার সময় চিকিৎসা সহায়তার দ্রুত অ্যাক্সেস - তাৎক্ষণিক সহায়তার জন্য যাত্রীদের রেলওয়ে কর্তৃপক্ষের সাথে সংযুক্ত করা',
        'for_passengers': 'যাত্রীদের জন্য',
        'for_passengers_subtitle': 'যাত্রীদের জন্য',
        'passenger_services': 'যাত্রী সেবা',
        'passenger_desc': 'জরুরি অবস্থার রিপোর্ট করতে, SOS সতর্কতা অ্যাক্সেস করতে, আপনার ট্রেন ট্র্যাক করতে লগইন প্রয়োজন',
        'login_to_access': 'পোর্টাল অ্যাক্সেস করতে লগইন করুন',
        'for_authorities': 'রেলওয়ে কর্তৃপক্ষের জন্য',
        'for_authorities_subtitle': 'রেলওয়ে কর্তৃপক্ষের জন্য',
        'authority_dashboard': 'কর্তৃপক্ষের ড্যাশবোর্ড',
        'authority_desc': 'জরুরি অবস্থা পর্যবেক্ষণ করুন, চিকিৎসা প্রতিক্রিয়া সমন্বয় করুন, ট্রেনের অবস্থান ট্র্যাক করুন',
        'access_authority': 'কর্তৃপক্ষের পোর্টাল অ্যাক্সেস করুন',
        
        # Dashboard Content
        'nearest_station': 'নিকটতম স্টেশন',
        'station_master_dashboard': 'স্টেশন মাস্টার ড্যাশবোর্ড',
        
        # Header & Footer
        'ministry_of_railways': 'রেল মন্ত্রণালয়',
        'emergency_support_system': 'জরুরি সহায়তা ব্যবস্থা',
        'railway_medical_emergency_response': 'রেলওয়ে চিকিৎসা জরুরি প্রতিক্রিয়া',
        'copyright': '© 2024 রেলওয়ে চিকিৎসা জরুরি প্রতিক্রিয়া ব্যবস্থা। রেল মন্ত্রণালয়।',
        
        # Emergency Banner
        'medical_emergency_question': 'চিকিৎসা জরুরি অবস্থা?',
        'need_immediate_assistance': 'ট্রেনে তাৎক্ষণিক চিকিৎসা সহায়তার প্রয়োজন?',
        'report_emergency_immediately': 'অবিলম্বে আপনার জরুরি অবস্থার রিপোর্ট করুন। রেলওয়ে কর্তৃপক্ষ নিকটতম স্টেশনে চিকিৎসা সহায়তার সমন্বয় করবে।',
        'report_medical_emergency_btn': '🚨 জরুরি অবস্থার রিপোর্ট করুন',
        'emergency_helpline': 'জরুরি হেল্পলাইন',
        'call': 'কল',
        'railway': 'রেলওয়ে',
        'national_emergency': 'জাতীয় জরুরি অবস্থা',
        
        # Info Section
        'dedicated_system_desc': 'ট্রেন যাত্রার সময় চিকিৎসা জরুরি অবস্থা রিপোর্ট করার জন্য একটি নিবেদিত ব্যবস্থা। স্টেশন ম্যানেজার এবং রেলওয়ে কর্মকর্তারা তাৎক্ষণিক চিকিৎসা সহায়তার সমন্বয় করতে পারেন।',
        'passenger_login': 'যাত্রী লগইন',
        'admin_login': 'অ্যাডমিন লগইন',
        'station_managers_access': 'স্টেশন ম্যানেজাররা ড্যাশবোর্ড অ্যাক্সেস করতে পারেন:',
        'view_all_reports': 'সমস্ত জরুরি রিপোর্ট দেখুন',
        'track_train_locations': 'ট্রেনের অবস্থান ট্র্যাক করুন',
        'coordinate_response': 'চিকিৎসা প্রতিক্রিয়া সমন্বয় করুন',
        'monitor_emergencies': 'স্টেশন মাস্টাররা তাদের স্টেশনের দিকে আসা জরুরি অবস্থা পর্যবেক্ষণ করতে পারেন:',
        'view_station_reports': 'স্টেশন-ভিত্তিক রিপোর্ট দেখুন',
        'prepare_medical_teams': 'চিকিৎসা দল প্রস্তুত করুন',
        'coordinate_local_response': 'স্থানীয় প্রতিক্রিয়া সমন্বয় করুন',
        
        # Quick Links
        'quick_links': 'দ্রুত লিঙ্ক',
        'crowd_monitor': 'ভিড় মনিটর',
        'medical_bot': '🤖 মেডিকেল বট',
        'all_services': 'সব পরিষেবা',
        'emergency_contacts': 'জরুরি যোগাযোগ',
        'ambulance': 'অ্যাম্বুলেন্স',
        
        # Important Info
        'important_information': 'গুরুত্বপূর্ণ তথ্য',
        'life_threatening_warning': 'জীবন-হুমকির জরুরি অবস্থার জন্য',
        'call_helpline_immediately': 'অবিলম্বে জরুরি হেল্পলাইন ১১২ বা রেলওয়ে হেল্পলাইন ১৩৯ কল করুন। গুরুতর জরুরি অবস্থার জন্য শুধুমাত্র এই ব্যবস্থার উপর নির্ভর করবেন না।',
        'system_limitations': 'এই ব্যবস্থা চিকিৎসা সহায়তা সমন্বয়ে সাহায্য করে কিন্তু জরুরি চিকিৎসা পরিষেবার বিকল্প নয়।',

        'distance': 'দূরত্ব',
        'contact': 'যোগাযোগ',
        'recommended_action': 'পরামর্শিত কার্যক্রম',
        'dispatch_medical_team': 'চিকিৎসা দল পাঠান',
        'calculating': 'গণনা করা হচ্ছে...',
        'timeline': 'সমযসীমা',
        'reported': 'রিপোর্ট করা হয়েছে',
        'status': 'অবস্থা',
        'eta_to_station': 'স্টেশনে পৌঁছানোর সময়',
        'minutes': 'মিনিট',
        'live_tracking': 'লাইভ ট্র্যাকিং',
        'medical_response': 'চিকিৎসা প্রতিক্রিয়া',
        'alert_manager': 'ম্যানেজারকে সতর্ক করুন',
        'no_station_found': 'কোন স্টেশন পাওয়া যায়নি',
        'mark_in_progress': 'চলমান হিসেবে চিহ্নিত করুন',
        'mark_resolved': 'সমাধান হিসেবে চিহ্নিত করুন',
        'no_active_reports': 'কোন সক্রিয় জরুরি রিপোর্ট নেই',
        'all_systems_operational': 'সব সিস্টেম পরিচালনায়। কোন চিকিৎসা জরুরি অবস্থা রিপোর্ট করা হয়নি।',
        'last_updated': 'শেষ আপডেট',
        'system_status': 'সিস্টেমের অবস্থা',
        'emergency_system': 'জরুরি সিস্টেম',
        'operational': 'পরিচালনায়',
        'active': 'সক্রিয়',
        'station_network': 'স্টেশন নেটওয়ার্ক',
        'connected': 'সংযুক্ত',
        'auto_refresh': 'অটো-রিফ্রেশ',
        'seconds': 'সেকেন্ড',
        
        # Additional Form Fields
        'emergency_details': 'জরুরি বিবরণ',
        'location': 'অবস্থান (ঐচ্ছিক)',
        'username': 'ব্যবহারকারীর নাম',
        
        # Station Master
        'for_station_masters': 'স্টেশন মাস্টারদের জন্য',
        'station_master_login': 'স্টেশন মাস্টার লগইন',
        'station_master_signin': 'স্টেশন মাস্টার সাইন-ইন',
        'station_master_desc': 'আপনার স্টেশনের জরুরি রিপোর্ট অ্যাক্সেস করুন এবং চিকিৎসা প্রতিক্রিয়া সমন্বয় করুন',
        'station_code': 'স্টেশন কোড',
        'password': 'পাসওয়ার্ড',
        'sign_in': 'সাইন ইন',
        'return_to_home': 'হোমে ফিরে যান',
        'station_master_portal': 'স্টেশন মাস্টার পোর্টাল',
        'authorized_personnel': 'শুধুমাত্র অনুমোদিত কর্মী',
        'railway_emergency_system': 'রেলওয়ে জরুরি ব্যবস্থা',
        'station_master_console': 'স্টেশন মাস্টার কনসোল',
        'station_emergency_management': 'স্টেশন জরুরি ব্যবস্থাপনা ও সমন্বয়',
        'passenger_site': 'যাত্রী সাইট',
        'emergency_reports_for_station': 'স্টেশনের জন্য জরুরি রিপোর্ট',
        'monitor_station_emergencies': 'আপনার স্টেশনে আসছে বা আছে এমন জরুরি অবস্থা পর্যবেক্ষণ করুন',
        'system_online': 'সিস্টেম: অনলাইন',
        'station_information': 'স্টেশন তথ্য',
        'station_name': 'স্টেশনের নাম',
        'contact_number': 'যোগাযোগ নম্বর',
        'medical_facility': 'চিকিৎসা সুবিধা',
        'station_overview': 'স্টেশন সংক্ষিপ্ত বিবরণ',
        'approaching_trains': 'আসছে ট্রেন',
        'pending_emergencies': 'অপেক্ষমান',
        'report_id': 'রিপোর্ট',
        'passenger': 'যাত্রী',
        'train': 'ট্রেন',
        'emergency': 'জরুরি অবস্থা',
        'eta': 'পৌঁছানোর সময়',
        'actions': 'কার্যক্রম',
        'prepare_medical_team': 'চিকিৎসা দল প্রস্তুত করুন',
        'nearby_hospitals': 'কাছাকাছি হাসপাতাল',
        'station_master_footer': 'স্টেশন মাস্টার কনসোল',
        'no_emergency_reports': 'আপনার স্টেশনের জন্য কোন জরুরি রিপোর্ট নেই',

    },
    
    'ml': {
        # Navigation
        'home': 'ഹോം',
        'emergency': 'അടിയന്തരാവസ്ഥ',
        'login': 'ലോഗിൻ',
        'signup': 'സൈൻ അപ്പ്',
        'dashboard': 'ഡാഷ്ബോർഡ്',
        'logout': 'ലോഗൗട്ട്',
        'track_train': 'ട്രെയിൻ ട്രാക്ക് ചെയ്യുക',
        
        # Emergency Form
        'report_emergency': 'അടിയന്തരാവസ്ഥ റിപ്പോർട്ട് ചെയ്യുക',
        'passenger_name': 'യാത്രക്കാരന്റെ പേര്',
        'phone_number': 'ഫോൺ നമ്പർ',
        'train_number': 'ട്രെയിൻ നമ്പർ',
        'coach_number': 'കോച്ച് നമ്പർ',
        'seat_number': 'സീറ്റ് നമ്പർ',
        'emergency_type': 'അടിയന്തര തരം',
        'description': 'വിവരണം',
        'submit_report': 'റിപ്പോർട്ട് സമർപ്പിക്കുക',
        'get_location': 'എന്റെ സ്ഥാനം നേടുക',
        
        # Emergency Types
        'heart_attack': 'ഹൃദയാഘാതം',
        'breathing_difficulty': 'ശ്വാസതടസ്സം',
        'severe_pain': 'കഠിനമായ വേദന',
        'unconscious': 'അബോധാവസ്ഥ',
        'injury_accident': 'പരിക്ക്/അപകടം',
        'high_fever': 'ഉയർന്ന പനി',
        'sos': 'SOS - ഗുരുതരമായ അടിയന്തരാവസ്ഥ',
        'other': 'മറ്റുള്ളവ',
        
        # Dashboard
        'emergency_reports': 'അടിയന്തര റിപ്പോർട്ടുകൾ',
        'total_reports': 'മൊത്തം റിപ്പോർട്ടുകൾ',
        'sos_alerts': 'SOS അലേർട്ടുകൾ',
        'pending': 'തീർപ്പുകൽപ്പിക്കാത്തത്',
        'resolved': 'പരിഹരിച്ചു',
        'system_status': 'സിസ്റ്റം നില',
        'emergency_system': 'അടിയന്തര സംവിധാനം',
        'train_tracking': 'ട്രെയിൻ ട്രാക്കിംഗ്',
        'station_network': 'സ്റ്റേഷൻ നെറ്റ്‌വർക്ക്',
        'operational': 'പ്രവർത്തനക്ഷമം',
        'active': 'സജീവം',
        'connected': 'ബന്ധിപ്പിച്ചിരിക്കുന്നു',
        
        # Train Info
        'train_name': 'ട്രെയിനിന്റെ പേര്',
        'source_station': 'ഉറവിട സ്റ്റേഷൻ',
        'destination_station': 'ലക്ഷ്യസ്ഥാന സ്റ്റേഷൻ',
        'current_location': 'നിലവിലെ സ്ഥാനം',
        'speed': 'വേഗത',
        'last_station': 'അവസാന സ്റ്റേഷൻ',
        'next_station': 'അടുത്ത സ്റ്റേഷൻ',
        'search_trains': 'ട്രെയിനുകൾ തിരയുക',
        'popular_trains': 'ജനപ്രിയ ട്രെയിനുകൾ',
        
        # Medical Response
        'medical_response': 'മെഡിക്കൽ പ്രതികരണം',
        'nearest_hospital': 'അടുത്തുള്ള ആശുപത്രി',
        'distance': 'ദൂരം',
        'contact': 'ബന്ധപ്പെടുക',
        'specialties': 'സ്പെഷ്യാലിറ്റികൾ',
        'ambulance_available': 'ആംബുലൻസ് ലഭ്യമാണ്',
        'emergency_available': 'അടിയന്തരാവസ്ഥ ലഭ്യമാണ്',
        
        # Status
        'in_progress': 'പുരോഗതിയിൽ',
        'mark_resolved': 'പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക',
        'alert_manager': 'മാനേജരെ അലേർട്ട് ചെയ്യുക',
        'live_tracking': 'ലൈവ് ട്രാക്കിംഗ്',
        
        # Messages
        'emergency_submitted': 'അടിയന്തര റിപ്പോർട്ട് വിജയകരമായി സമർപ്പിച്ചു!',
        'help_dispatched': 'മെഡിക്കൽ സഹായം അടുത്തുള്ള സ്റ്റേഷനിലേക്ക് അയച്ചു.',
        'login_required': 'അടിയന്തരാവസ്ഥ റിപ്പോർട്ട് ചെയ്യാൻ ദയവായി ലോഗിൻ ചെയ്യുക',
        'invalid_credentials': 'തെറ്റായ ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ്',
        'account_created': 'അക്കൗണ്ട് വിജയകരമായി സൃഷ്ടിച്ചു',
        'username_exists': 'ഉപയോക്തൃനാമം അല്ലെങ്കിൽ ഇമെയിൽ ഇതിനകം നിലവിലുണ്ട്',
        
        # Page Content
        'page_title': 'റെയിൽവേ യാത്രക്കാർക്കുള്ള അടിയന്തര മെഡിക്കൽ സഹായം',
        'page_subtitle': 'ട്രെയിൻ യാത്രയിൽ മെഡിക്കൽ സഹായത്തിനുള്ള വേഗത്തിലുള്ള പ്രവേശനം - ഉടനടി സഹായത്തിനായി യാത്രക്കാരെ റെയിൽവേ അധികാരികളുമായി ബന്ധിപ്പിക്കുന്നു',
        'for_passengers': 'യാത്രക്കാർക്കായി',
        'for_passengers_subtitle': 'യാത്രക്കാർക്കായി',
        'passenger_services': 'യാത്രക്കാരുടെ സേവനങ്ങൾ',
        'passenger_desc': 'അടിയന്തരാവസ്ഥകൾ റിപ്പോർട്ട് ചെയ്യാൻ, SOS അലേർട്ടുകൾ ആക്സസ് ചെയ്യാൻ, നിങ്ങളുടെ ട്രെയിൻ ട്രാക്ക് ചെയ്യാൻ ലോഗിൻ ആവശ്യമാണ്',
        'login_to_access': 'പോർട്ടൽ ആക്സസ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക',
        'for_authorities': 'റെയിൽവേ അധികാരികൾക്കായി',
        'for_authorities_subtitle': 'റെയിൽവേ അധികാരികൾക്കായി',
        'authority_dashboard': 'അതോറിറ്റി ഡാഷ്ബോർഡ്',
        'authority_desc': 'അടിയന്തരാവസ്ഥകൾ നിരീക്ഷിക്കുക, മെഡിക്കൽ പ്രതികരണം ഏകോപിപ്പിക്കുക, ട്രെയിൻ ലൊക്കേഷനുകൾ ട്രാക്ക് ചെയ്യുക',
        'access_authority': 'അതോറിറ്റി പോർട്ടൽ ആക്സസ് ചെയ്യുക',
        
        # Dashboard Content
        'nearest_station': 'അടുത്തുള്ള സ്റ്റേഷന്',
        'distance': 'ദൂരം',
        'contact': 'ബന്ധപ്പെടുക',
        'recommended_action': 'ശിഫാരസു ചെയ്യുന്ന നടപടി',
        'dispatch_medical_team': 'മെഡിക്കൽ ടീം അയയ്ക്കുക',
        'calculating': 'കണക്കാക്കുന്നു...',
        'timeline': 'സമയരേഖ',
        'reported': 'റിപ്പോർട്ട് ചെയ്തു',
        'status': 'സ്ഥിതി',
        'eta_to_station': 'സ്റ്റേഷനിലെത്താനുള്ള സമയം',
        'minutes': 'മിനിറ്റുകൾ',
        'live_tracking': 'ലൈവ് ട്രാക്കിംഗ്',
        'medical_response': 'മെഡിക്കൽ പ്രതികരണം',
        'alert_manager': 'മാനേജരെ അലേർട്ട് ചെയ്യുക',
        'no_station_found': 'സ്റ്റേഷന് കണ്ടെത്തിയില്ല',
        'mark_in_progress': 'പുരോഗതിയിലാണെന്ന് അടയാളപ്പെടുത്തുക',
        'mark_resolved': 'പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക',
        'no_active_reports': 'സക്രിയ അടിയന്തര റിപ്പോർട്ടുകൾ ഇല്ല',
        'all_systems_operational': 'എല്ലാ സിസ്റ്റങ്ങളും പരിചാലനയിലാണ്. മെഡിക്കൽ അടിയന്തരാവസ്ഥകൾ റിപ്പോർട്ട് ചെയ്തിട്ടില്ല.',
        'last_updated': 'അവസാനം അപ്ഡേറ്റ് ചെയ്തത്',
        'system_status': 'സിസ്റ്റം സ്ഥിതി',
        'emergency_system': 'അടിയന്തര സിസ്റ്റം',
        'operational': 'പരിചാലനയിലാണ്',
        'active': 'സക്രിയം',
        'station_network': 'സ്റ്റേഷന് നെറ്റ്വർക്ക്',
        'connected': 'ബന്ധിപ്പിച്ചിരിക്കുന്നു',
        'auto_refresh': 'ഓടോ-രിഫ്രെഷ്',
        'seconds': 'സെക്കന്റുകൾ',
        
        # Header & Footer
        'ministry_of_railways': 'Ministry of Railways',
        'emergency_support_system': 'Emergency Support System',
        'railway_medical_emergency_response': 'Railway Medical Emergency Response',
        'copyright': '© 2024 Railway Medical Emergency Response System. Ministry of Railways.',
        
        # Emergency Banner
        'medical_emergency_question': 'Medical Emergency?',
        'need_immediate_assistance': 'Need immediate medical assistance on train?',
        'report_emergency_immediately': 'Report your emergency immediately. Railway authorities will coordinate medical assistance at the nearest station.',
        'report_medical_emergency_btn': '🚨 Report Medical Emergency',
        'emergency_helpline': 'Emergency Helpline',
        'call': 'Call',
        'railway': 'Railway',
        'national_emergency': 'National Emergency',
        
        # Info Section
        'dedicated_system_desc': 'A dedicated system for reporting medical emergencies during train journeys. Station managers and railway officials can coordinate immediate medical assistance.',
        'passenger_login': 'Passenger Login',
        'admin_login': 'Admin Login',
        'station_managers_access': 'Station managers and authorized personnel can access the dashboard to:',
        'view_all_reports': 'View all emergency reports',
        'track_train_locations': 'Track train locations',
        'coordinate_response': 'Coordinate medical response',
        'monitor_emergencies': 'Station masters can monitor emergencies approaching their station:',
        'view_station_reports': 'View station-specific reports',
        'prepare_medical_teams': 'Prepare medical teams',
        'coordinate_local_response': 'Coordinate local response',
        
        # Quick Links
        'quick_links': 'Quick Links',
        'crowd_monitor': 'Crowd Monitor',
        'medical_bot': '🤖 Medical Bot',
        'all_services': 'All Services',
        'emergency_contacts': 'Emergency Contacts',
        'ambulance': 'Ambulance',
        
        # Important Info
        'important_information': 'Important Information',
        'life_threatening_warning': 'For Life-Threatening Emergencies',
        'call_helpline_immediately': 'Call emergency helpline 112 or railway helpline 139 immediately. Do not rely solely on this system for critical emergencies.',
        'system_limitations': 'This system assists in coordinating medical assistance but does not replace emergency medical services. Always call emergency services for immediate life-threatening situations.',
        
        'station_master_dashboard': 'Station Master Dashboard'
    }
}

def get_translation(lang_code, key, default=None):
    """Get translation for a key in specified language"""
    if lang_code in TRANSLATIONS and key in TRANSLATIONS[lang_code]:
        return TRANSLATIONS[lang_code][key]
    elif key in TRANSLATIONS['en']:
        return TRANSLATIONS['en'][key]  # Fallback to English
    return default or key

def get_available_languages():
    """Get list of available languages"""
    return LANGUAGES